name: Upload Docker Images  to Registry

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Docker Build Image
        run: |
          docker build . -t tuxroy/ngnix:1.0.0 
      -
        name: Push Image
        run: |
          docker push tuxroy/ngnix:1.0.0
